{% set name = "gftool" %}
{% set version = "0.11.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gftool-{{ version }}.tar.gz
  sha256: d10d1fb751a1cdd0e6385958f5528525d8cbfbc30acdae69d0f2d1b0ff2f9ba5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.7
  run:
    - mpmath
    - numpy >=1.17.0
    - python >=3.7
    - scipy >=1.6.0

test:
  imports:
    - gftool
    - gftool.basis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DerWeh/gftools
  summary: Collection of commonly used Green's functions and utilities
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://gftools.readthedocs.io
  dev_url: https://github.com/DerWeh/gftools

extra:
  recipe-maintainers:
    - DerWeh
