{% set name = "gftool" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gftool-{{ version }}.tar.gz
  sha256: 4f408704f2ea5936cd21cc81651002cc2c1f9b15a89f83a58e89eeaffda3f379

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
  run:
    - mpmath
    - numpy >=1.17.0
    - python >={{ python_min }}
    - scipy >=1.6.0

test:
  imports:
    - gftool
    - gftool.basis
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/DerWeh/gftools
  summary: Collection of commonly used Green's functions and utilities
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://gftools.readthedocs.io
  dev_url: https://github.com/DerWeh/gftools

extra:
  recipe-maintainers:
    - DerWeh
