{% set name = "gftool" %}
{% set version = "0.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gftool-{{ version }}.tar.gz
  sha256: 107e39fe89ccf730238002b0fed0191b9b56663f01bb2e740c975c9ffe518e7f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.7
  run:
    - mpmath
    - numpy >=1.17.0
    - python >=3.7
    - scipy

test:
  imports:
    - gftool
    - gftool.basis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DerWeh/gftools
  summary: Collection of commonly used Green's functions and utilities
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://gftools.readthedocs.io
  dev_url: https://github.com/DerWeh/gftools

extra:
  recipe-maintainers:
    - DerWeh
