{% set name = "gftool" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gftool-{{ version }}.tar.gz
  sha256: d25cee707b3f3245a50d157391a1fd9a87b7ac5e1b346ab5cf283d040f2f3806

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - mpmath
    - numpy
    - python >=3.6
    - scipy

test:
  imports:
    - gftool
    - gftool.basis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DerWeh/gftools
  summary: Collection of commonly used Green's functions and utilities
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://gftools.readthedocs.io
  dev_url: https://github.com/DerWeh/gftools

extra:
  recipe-maintainers:
    - DerWeh
